import kexec-tools-2.0.26-8.el9

diff --git a/SOURCES/kdumpctl b/SOURCES/kdumpctl
--- a/SOURCES/kdumpctl
+++ b/SOURCES/kdumpctl
@@ -42,6 +42,13 @@ if ! dlog_init; then
 	exit 1
 fi
 
+KDUMP_TMPDIR=$(mktemp --tmpdir -d kdump.XXXX)
+trap '
+    ret=$?;
+    rm -rf "$KDUMP_TMPDIR"
+    exit $ret;
+    ' EXIT
+
 single_instance_lock()
 {
 	local rc timeout=5 lockfile
@@ -655,7 +662,7 @@ function remove_kdump_kernel_key()
 # as the currently running kernel.
 load_kdump()
 {
-	local ret
+	local ret uki
 
 	KEXEC_ARGS=$(prepare_kexec_args "${KEXEC_ARGS}")
 	KDUMP_COMMANDLINE=$(prepare_cmdline "${KDUMP_COMMANDLINE}" "${KDUMP_COMMANDLINE_REMOVE}" "${KDUMP_COMMANDLINE_APPEND}")
@@ -667,6 +674,16 @@ load_kdump()
 		dinfo "Secure Boot is enabled. Using kexec file based syscall."
 		KEXEC_ARGS="$KEXEC_ARGS -s"
 		load_kdump_kernel_key
+	fi
+
+	if is_uki "$KDUMP_KERNEL"; then
+		uki=$KDUMP_KERNEL
+		KDUMP_KERNEL=$KDUMP_TMPDIR/vmlinuz
+		objcopy -O binary --only-section .linux "$uki" "$KDUMP_KERNEL"
+		sync -f "$KDUMP_KERNEL"
+		# Make sure the temp file has the correct SELinux label.
+		# Otherwise starting the kdump.service will fail.
+		chcon -t boot_t "$KDUMP_KERNEL"
 	fi
 
 	ddebug "$KEXEC $KEXEC_ARGS $standard_kexec_args --command-line=$KDUMP_COMMANDLINE --initrd=$TARGET_INITRD $KDUMP_KERNEL"
@@ -1219,6 +1236,77 @@ rebuild()
 	return $?
 }
 
+check_vmlinux()
+{
+	# Use readelf to check if it's a valid ELF
+	readelf -h "$1" &> /dev/null || return 1
+}
+
+get_vmlinux_size()
+{
+	local size=0 _msize
+
+	while read -r _msize; do
+		size=$((size + _msize))
+	done <<< "$(readelf -l -W "$1" | awk '/^  LOAD/{print $6}' 2> /dev/stderr)"
+
+	echo $size
+}
+
+try_decompress()
+{
+	# The obscure use of the "tr" filter is to work around older versions of
+	# "grep" that report the byte offset of the line instead of the pattern.
+
+	# Try to find the header ($1) and decompress from here
+	for pos in $(tr "$1\n$2" "\n$2=" < "$4" | grep -abo "^$2"); do
+		if ! type -P "$3" > /dev/null; then
+			ddebug "Signiature detected but '$3' is missing, skip this decompressor"
+			break
+		fi
+
+		pos=${pos%%:*}
+		tail "-c+$pos" "$img" | $3 > "$5" 2> /dev/null
+		if check_vmlinux "$5"; then
+			ddebug "Kernel is extracted with '$3'"
+			return 0
+		fi
+	done
+
+	return 1
+}
+
+# Borrowed from linux/scripts/extract-vmlinux
+get_kernel_size()
+{
+	# Prepare temp files:
+	local tmp img=$1
+
+	tmp="$KDUMP_TMPDIR/vmlinux"
+
+	# Try to check if it's a vmlinux already
+	check_vmlinux "$img" && get_vmlinux_size "$img" && return 0
+
+	# That didn't work, so retry after decompression.
+	try_decompress '\037\213\010' xy gunzip "$img" "$tmp" ||
+		try_decompress '\3757zXZ\000' abcde unxz "$img" "$tmp" ||
+		try_decompress 'BZh' xy bunzip2 "$img" "$tmp" ||
+		try_decompress '\135\0\0\0' xxx unlzma "$img" "$tmp" ||
+		try_decompress '\211\114\132' xy 'lzop -d' "$img" "$tmp" ||
+		try_decompress '\002!L\030' xxx 'lz4 -d' "$img" "$tmp" ||
+		try_decompress '(\265/\375' xxx unzstd "$img" "$tmp"
+
+	# Finally check for uncompressed images or objects:
+	[[ $? -eq 0 ]] && get_vmlinux_size "$tmp" && return 0
+
+	# Fallback to use iomem
+	local _size=0 _seg
+	while read -r _seg; do
+		_size=$((_size + 0x${_seg#*-} - 0x${_seg%-*}))
+	done <<< "$(grep -E "Kernel (code|rodata|data|bss)" /proc/iomem | cut -d ":" -f 1)"
+	echo $_size
+}
+
 do_estimate()
 {
 	local kdump_mods
@@ -1382,10 +1470,13 @@ _filter_grubby_kernel_str()
 _find_kernel_path_by_release()
 {
 	local _release="$1" _grubby_kernel_str _kernel_path
-	_grubby_kernel_str=$(grubby --info ALL | grep "^kernel=.*$_release\"$")
+
+	# Insert '/' before '+' to cope with grep's EREs
+	_release=${_release//+/\\+}
+	_grubby_kernel_str=$(grubby --info ALL | grep -E "^kernel=.*$_release(\/\w+)?\"$")
 	_kernel_path=$(_filter_grubby_kernel_str "$_grubby_kernel_str")
 	if [[ -z $_kernel_path ]]; then
-		derror "kernel $_release doesn't exist"
+		ddebug "kernel $_release doesn't exist"
 		return 1
 	fi
 	echo -n "$_kernel_path"
@@ -1647,72 +1738,39 @@ _is_bootloader_installed()
 	fi
 }
 
-# update the crashkernel value in GRUB_ETC_DEFAULT if necessary
-#
-# called by reset_crashkernel_after_update and inherit its array variable
-# _crashkernel_vals
-update_crashkernel_in_grub_etc_default_after_update()
+_update_crashkernel()
 {
-	local _crashkernel _fadump_val
-	local _dump_mode _old_default_crashkernel _new_default_crashkernel
+	local _kernel _kver _dump_mode _old_default_crashkernel _new_default_crashkernel _fadump_val _msg
 
-	if [[ $(uname -m) == s390x ]]; then
-		return
-	fi
-
-	_crashkernel=$(_read_kernel_arg_in_grub_etc_default crashkernel)
-
-	if [[ -z $_crashkernel ]]; then
-		return
-	fi
-
-	_fadump_val=$(_read_kernel_arg_in_grub_etc_default fadump)
-	_dump_mode=$(get_dump_mode_by_fadump_val "$_fadump_val")
-
-	_old_default_crashkernel=${_crashkernel_vals[old_${_dump_mode}]}
-	_new_default_crashkernel=${_crashkernel_vals[new_${_dump_mode}]}
-
-	if [[ $_crashkernel == auto ]] ||
-		  [[ $_crashkernel == "$_old_default_crashkernel" &&
-		     $_new_default_crashkernel != "$_old_default_crashkernel" ]]; then
-			_update_kernel_arg_in_grub_etc_default crashkernel "$_new_default_crashkernel"
+	_kernel=$1
+	_dump_mode=$(get_dump_mode_by_kernel "$_kernel")
+	_old_default_crashkernel=$(get_grub_kernel_boot_parameter "$_kernel" crashkernel)
+	_kver=$(parse_kver_from_path "$_kernel")
+	# The second argument is for the case of aarch64, where installing a 64k variant on a 4k kernel, or vice versa
+	_new_default_crashkernel=$(kdump_get_arch_recommend_crashkernel "$_dump_mode" "$_kver")
+	if [[ $_old_default_crashkernel != "$_new_default_crashkernel" ]]; then
+		_fadump_val=$(get_grub_kernel_boot_parameter "$_kernel" fadump)
+		if _update_kernel_cmdline "$_kernel" "$_new_default_crashkernel" "$_dump_mode" "$_fadump_val"; then
+			_msg="For kernel=$_kernel, crashkernel=$_new_default_crashkernel now. Please reboot the system for the change to take effet."
+			_msg+=" Note if you don't want kexec-tools to manage the crashkernel kernel parameter, please set auto_reset_crashkernel=no in /etc/kdump.conf."
+			dinfo "$_msg"
+		fi
 	fi
 }
+
 
 # shellcheck disable=SC2154 # false positive when dereferencing an array
 reset_crashkernel_after_update()
 {
-	local _kernel _crashkernel _dump_mode _fadump_val _old_default_crashkernel _new_default_crashkernel
-	declare -A _crashkernel_vals
+	local _kernel
 
 	if ! _is_bootloader_installed; then
 		return
 	fi
 
-	_crashkernel_vals[old_kdump]=$(cat /tmp/old_default_crashkernel 2> /dev/null)
-	_crashkernel_vals[old_fadump]=$(cat /tmp/old_default_crashkernel_fadump 2> /dev/null)
-	_crashkernel_vals[new_kdump]=$(get_default_crashkernel kdump)
-	_crashkernel_vals[new_fadump]=$(get_default_crashkernel fadump)
-
 	for _kernel in $(_get_all_kernels_from_grubby ALL); do
-		_crashkernel=$(get_grub_kernel_boot_parameter "$_kernel" crashkernel)
-		if [[ $_crashkernel == auto ]]; then
-			reset_crashkernel "--kernel=$_kernel"
-		elif [[ -n $_crashkernel ]]; then
-			_dump_mode=$(get_dump_mode_by_kernel "$_kernel")
-			_old_default_crashkernel=${_crashkernel_vals[old_${_dump_mode}]}
-			_new_default_crashkernel=${_crashkernel_vals[new_${_dump_mode}]}
-			if [[ $_crashkernel == "$_old_default_crashkernel" ]] &&
-				[[ $_new_default_crashkernel != "$_old_default_crashkernel" ]]; then
-				_fadump_val=$(get_grub_kernel_boot_parameter "$_kernel" fadump)
-				if _update_kernel_cmdline "$_kernel" "$_new_default_crashkernel" "$_dump_mode" "$_fadump_val"; then
-					echo "For kernel=$_kernel, crashkernel=$_new_default_crashkernel now."
-				fi
-			fi
-		fi
+		_update_crashkernel "$_kernel"
 	done
-
-	update_crashkernel_in_grub_etc_default_after_update
 }
 
 # read the value of an environ variable from given environ file path
@@ -1736,8 +1794,7 @@ _is_osbuild()
 
 reset_crashkernel_for_installed_kernel()
 {
-	local _installed_kernel _running_kernel _crashkernel _crashkernel_running
-	local _dump_mode_running _fadump_val_running
+	local _installed_kernel
 
 	# During package install, only try to reset crashkernel for osbuild
 	# thus to avoid calling grubby when installing os via anaconda
@@ -1756,23 +1813,7 @@ reset_crashkernel_for_installed_kernel()
 		return
 	fi
 
-	if ! _running_kernel=$(_get_current_running_kernel_path); then
-		derror "Couldn't find current running kernel"
-		exit
-	fi
-
-	_crashkernel=$(get_grub_kernel_boot_parameter "$_installed_kernel" crashkernel)
-	_crashkernel_running=$(get_grub_kernel_boot_parameter "$_running_kernel" crashkernel)
-	_dump_mode_running=$(get_dump_mode_by_kernel "$_running_kernel")
-	_fadump_val_running=$(get_grub_kernel_boot_parameter "$_kernel" fadump)
-
-	if [[ $_crashkernel != "$_crashkernel_running" ]]; then
-		if _update_kernel_cmdline "$_installed_kernel" "$_crashkernel_running" "$_dump_mode_running" "$_fadump_val_running"; then
-			echo "kexec-tools has reset $_installed_kernel to use the new default crashkernel value $_crashkernel_running"
-		fi
-	elif [[ $_crashkernel == auto ]]; then
-		reset_crashkernel "--kernel=$_installed_kernel"
-	fi
+	_update_crashkernel "$_installed_kernel"
 }
 
 if [[ ! -f $KDUMP_CONFIG_FILE ]]; then
